language: python
python: 2.7
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg 
  - bin/buildout -c travis.cfg
script: 
  - bin/test
  - bin/coverage run bin/test
after_success:
  - pip install -q coveralls==0.5
  - coveralls
notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.org#imio"
    on_success: change
    on_failure: always
